### ISSUE TITLE
Autoscaling in compactor

### ISSUE THREAD

**Issue by pandakkkk** [openobserve/openobserve-helm-chart#10]
Why is the autoscaling option not provided for the compactor? I can observe that other components already possess this feature.

**Comment by pandakkkk** [comment]
May I raise a pull request to make modifications, or is this intentional?

**Comment by prabhatsharma** [comment]
Wait for this. compactor could not autoscale horizontally earlier. It can now, but it's not well-tested yet. Will do it shortly.

**Comment by pandakkkk** [comment]
Thank you for the information. I understand now. It would be great if Autoscaling could be tailored to specific components, just like resource configuration, rather than being applied universally. This would allow for more flexibility and efficiency in the system. I appreciate your consideration of this suggestion.

**Comment by prabhatsharma** [comment]
Its now available
