### ISSUE TITLE
OpenTelemetryCollector v1alpha1 is deprecated. Migrate to v1beta1.

### ISSUE THREAD

**Issue by PandeoF1** [openobserve/openobserve-helm-chart#102]
Hi, is it possible to migrate from v1alpha1 to v1beta1 ?

Thx in advance for your return !

**Comment by prabhatsharma** [comment]
Tried a month ago. Did not work well. Will try again in some time. I could use some help here if someone can lend a hand.

**Comment by PandeoF1** [comment]
If you a have branch for that i can probably help you with that change ^^

**Comment by prabhatsharma** [comment]
Feel free to fork and create a PR.

**Comment by PandeoF1** [comment]
PR Merged so i close this issue
