### ISSUE TITLE
Add a OpenObserve not HA deployment

### ISSUE THREAD

**Issue by PandeoF1** [openobserve/openobserve-helm-chart#107]
Hi, i was thinking about creating a helm to generate OpenObserve deployment but without 900 splitted services (i talk an helm like docker compose)
IDK if it can be useless to add it here so i prefer to ask before doing my job and making a PR for nothing (Because if it's useless i will adapt it for my need...)

**Comment by prabhatsharma** [comment]
You already have a standalone helm chart that you could use - https://github.com/openobserve/openobserve-helm-chart/tree/main/charts/openobserve-standalone
