### ISSUE TITLE
HPA configuraation

### ISSUE THREAD

**Issue by pandakkkk** [openobserve/openobserve-helm-chart#12]
While exploring hpa config, I found that current HPA configuration for each components except ingester has incorrect target ref name "openobserve". It should be "openobserve-component_name " .

**Comment by prabhatsharma** [comment]
actually, multiple references were wrong for HPA. fixed it.

**Comment by pandakkkk** [comment]
@prabhatsharma thanks  for the speedy fix! 🙌
