### ISSUE TITLE
Allow non-selector pod labels

### ISSUE THREAD

**Issue by MOZGIII** [openobserve/openobserve-helm-chart#15]
I'd like to add a custom label to the pod templates that would not be part of the pod selectors.

In particular, I'd like to add `vector.dev/exclude: "true"` label.

However, it doesn't seem like the current design makes it possible.

**Comment by prabhatsharma** [comment]
You can add a labels section in values.yaml files and provide anything that you want. We did not have an empty `labels` section in values.yaml. I have added that now.

You could add below in values.yaml:

```yaml
labels:
  vector.dev/exclude: "true"
```

**Comment by MOZGIII** [comment]
From what I've read it doesn't seem to add the label to the pod template.

They work for the stateful set itself:

https://github.com/openobserve/openobserve-helm-chart/blob/e7d2cf293c51e2515f95aab1cfec4732e53e23a8/templates/ingester-statefulset.yaml#L6-L7

But not the pod template in it:

https://github.com/openobserve/openobserve-helm-chart/blob/e7d2cf293c51e2515f95aab1cfec4732e53e23a8/templates/ingester-statefulset.yaml#L23-L25

pod template allows adding labels, but only those that would also be selectors:

https://github.com/openobserve/openobserve-helm-chart/blob/e7d2cf293c51e2515f95aab1cfec4732e53e23a8/templates/ingester-statefulset.yaml#L12C12-L15

**Comment by prabhatsharma** [comment]
done
