### ISSUE TITLE
release git tag for new versions of the helm chart

### ISSUE THREAD

**Issue by nitredfv** [openobserve/openobserve-helm-chart#16]
I think it makes sense if there was a git tag for every new version of the helm chart.

This way someone like me would be able to find and download the `values.yaml` file that works for a specific version/tag of the helm chart instead of going through the git history. The last tag that was released is [v0.2.5](https://github.com/openobserve/openobserve-helm-chart/releases/tag/v0.2.5) which still uses `repository: public.ecr.aws/zinclabs/zincobserve`.

Thanks for the effort and the great project :+1:

**Comment by prabhatsharma** [comment]
agree. we will start tagging from now on.

**Comment by prabhatsharma** [comment]
latest tag is 0.5.36 . We will match the tags with the chart version to keep things simpler.
