### ISSUE TITLE
Wrong image tag in latest helm chart

### ISSUE THREAD

**Issue by ndtmdsma** [openobserve/openobserve-helm-chart#18]
Image tag in latest tagged helm chart release is set to `0.5.2`, whereas it should be `v0.5.2`, as that's what is published at https://gallery.ecr.aws/zinclabs/openobserve

Lots of:

`Failed to pull image "public.ecr.aws/zinclabs/openobserve:0.5.2": rpc error: code = NotFound desc = failed to pull and unpack image "public.ecr.aws/zinclabs/openobserve:0.5.2": failed to resolve reference "public.ecr.aws/zinclabs/openobserve:0.5.2": public.ecr.aws/zinclabs/openobserve:0.5.2: not found
`

https://github.com/openobserve/openobserve-helm-chart/blob/c04675c658ed2c7c53a6328e8f4c06058eb0c805/values.yaml#L9

I specified the right tag in my values overrides, so not a big deal, still, it'd be nice to have this right in the helm chart release.

**Comment by prabhatsharma** [comment]
fixed with new release
