### ISSUE TITLE
Ingester HPA must use StatefulSet not Statefulset

### ISSUE THREAD

**Issue by ndtmdsma** [openobserve/openobserve-helm-chart#19]
Horizontal Pod Autoscaler for ingester needs to reference `StatefulSet`, not `Statefulset` - it's case sensitive.

With the current configuration it says: 

> the HPA controller was unable to get the target's current scale: no matches for kind "Statefulset" in group "apps"

https://github.com/openobserve/openobserve-helm-chart/blob/efe24d0ab41354c92cc07ac51a0b2dd2354712a6/templates/ingester-hpa.yaml#L12

Editing tha hpa resource and changing it to correct value does indeed fix that:

> the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)

**Comment by prabhatsharma** [comment]
fixed
