### ISSUE TITLE
For local mode only single node deployment is allowed

### ISSUE THREAD

**Issue by autokilla47** [openobserve/openobserve-helm-chart#20]
Run helm with this diff:
```
$ diff my-values.yaml values.yaml
49c49
<   alertmanager: 0
---
>   alertmanager: 1
56c56
<     storageClass: "vcd-disk-dev"
---
>     storageClass: ""
66c66
<   ZO_ROOT_USER_PASSWORD: "Admin123"
---
>   ZO_ROOT_USER_PASSWORD: "Complexpass#123"
74c74
<   ZO_LOCAL_MODE: "true"
---
>   ZO_LOCAL_MODE: "false"
281c281
<   enabled: false # if true then etcd will be deployed as part of openobserve
---
>   enabled: true # if true then etcd will be deployed as part of openobserve
```
I set ZO_LOCAL_MODE: true, because i would like install a single node in my k8s cluster.
`$ helm install openobserve -f ./my-values.yaml . -n openobserve`
And all my pods (openobserve-router, openobserve-compactor, openobserve-ingester and openobserve-querier) have the same errors in the logs:
```
[2023-09-26T14:13:32Z INFO  openobserve] Starting OpenObserve v0.6.3
[2023-09-26T14:13:32Z INFO  openobserve] System info: CPU cores 4, MEM total 3640 MB, Disk total 25 GB, free 10 GB
thread 'main' panicked at 'For local mode only single node deployment is allowed!', /app/src/common/infra/cluster.rs:103:13
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
What is the problem? Why won't the pods start?

OpenObserve v0.6.3
chart version 0.5.38

**Comment by prabhatsharma** [comment]
helm chart does not support single node installation. Please use the statefulset from quickstart for now - https://openobserve.ai/docs/quickstart/#self-hosted-installation

**Comment by autokilla47** [comment]
found a solution https://github.com/mshade/openobserve-chart
