### ISSUE TITLE
move etc credentials to kubernetes secret

### ISSUE THREAD

**Issue by genofire** [openobserve/openobserve-helm-chart#23]
that is not really a good pattern:
https://github.com/openobserve/openobserve-helm-chart/blob/af446b5e829bf84e2c4a1c2f722537d9071d704c/charts/openobserve/templates/configmap.yaml#L97C40-L97C56

---

maybe you like todo it for cert files eigther

**Comment by prabhatsharma** [comment]
Agree. Will do it later.

**Comment by prabhatsharma** [comment]
We don't need to do this anymore as etcd does not store any data anymore and being used only for coordination. Data storage has been moved to Postgres/MySQL
