### ISSUE TITLE
Init containers registry configuration

### ISSUE THREAD

**Issue by srstrickland** [openobserve/openobserve-helm-chart#39]
Init containers are used in several places and are hard coded to `busybox` ([example](https://github.com/openobserve/openobserve-helm-chart/blob/main/charts/openobserve/templates/ingester-statefulset.yaml#L38)).  There should be some kind of way to configure a different registry via `values.yaml` so I can point at my own (caching) mirror, as pulling from dockerhub can result in rate limiting.

**Comment by prabhatsharma** [comment]
added busybox image to values.yaml. Also changed default registry to ECR
