### ISSUE TITLE
deploy openobserve-collector error!

### ISSUE THREAD

**Issue by sunshinejdq** [openobserve/openobserve-helm-chart#43]
Deploy according to document content
1. Install cert-manager
2. Update helm repo
3. Install OpenTelemetry operator
4. Create namespace
5. Install OpenObserve collector
no pod and no event
![7139a43ad093d3b0b58b310d695698f](https://github.com/openobserve/openobserve-helm-chart/assets/5857762/cbb8cf22-0d33-4263-af13-fef3e0813f24)
![85aafd18006cb7c0ea9bc467dc111b6](https://github.com/openobserve/openobserve-helm-chart/assets/5857762/b1eb0797-a760-4b4c-8684-e8b5b09f0dc9)
![1c6883f851026865356e181990f789c](https://github.com/openobserve/openobserve-helm-chart/assets/5857762/b320b301-d374-49f5-93d9-2f3b0f2e7256)

k8s version: 1.22.15

**Comment by prabhatsharma** [comment]
Warning messages can be safely ignored. 

>no pod and no event
What does this mean? No pods of openobserve-collector are being created?

Are there any deployments o statefulsets being created?

**Comment by Borrelhapje** [comment]
@sunshinejdq you may want to roll those authorization: basic credentials, just in case.
