### ISSUE TITLE
Load config and secret with an immutable .env

### ISSUE THREAD

**Issue by julienkosinski** [openobserve/openobserve-helm-chart#46]
Hello,

As far as I understand OpenObserve config, secrets included, are loaded through environment variables or a .env file.  In general both methods are considered secure but there's a debate about using environment variables in Kubernetes. The best security practice seems to mount an ephemeral volume with the secrets (in our case a .env with both secrets and config). This allows fine tuned permissions on the file and configuration immutability using immutable ephemeral volumes.

Would you be interested in a pull request implementing this?

For Kubernetes, see, for instance: 
https://blog.nillsf.com/index.php/2020/02/24/dont-use-environment-variables-in-kubernetes-to-consume-secrets/
https://medium.com/israeli-tech-radar/favor-config-files-over-env-vars-d9189d53c4b8

About immutability:
https://www.linkedin.com/pulse/deep-dive-kubernetes-immutable-secrets-configmaps-enhancing-i8iic
This proposal is implemented but the doc don't seems to be up to date: https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/1412-immutable-secrets-and-configmaps/README.md

Thank you very much.

**Comment by prabhatsharma** [comment]
Thanks @julienkosinski . This is a good concept but I think this is taking things a bit too far.
