### ISSUE TITLE
Have you considered saving logs in k8s into different streams

### ISSUE THREAD

**Issue by klboke** [openobserve/openobserve-helm-chart#50]
Considering that a typical company's business logs are distributed across different applications, with some applications generating a very large volume of logs while most have a minimal amount of logs, we aim to have the default applications follow the standard stream for transmission. However, when we encounter applications with exceptionally high log traffic, we will create a new stream specifically for these applications. This approach has many benefits, as it allows for more efficient and application-friendly performance in both writing and querying logs.

- A potential implementation approach: using k8s labels for routing

**Comment by prabhatsharma** [comment]
You can use routing processor to do this - https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/routingprocessor/README.md
