### ISSUE TITLE
Issue when upgrading from 0.9.1 to 0.10.1

### ISSUE THREAD

**Issue by ericsheris-rumble** [openobserve/openobserve-helm-chart#57]
Hello,
I just tried to update to 0.10.1 as mentioned above. Everything was looking ok. I run 4 ingesters, 1 of them successfully started, etcd, compactors, router, etc all started fine, but 3 of my ingesters just kept crashlooping with an error, something along the lines of `assertion `left == right` failed`. I swapped back to 0.9.1 and everything is fine, but now all my streams are doubled and I can't delete the doubled ones. in the screen shot it will be all the ones with a `/1712877810775363` 
First question here is, how can i get rid of these duplicate streams. the delete button in the UI just errors.

I can try to regenerate the error tomorrow evening and set rust_backtrace to 1.
If it matters, I run an external postgres db.

![image](https://github.com/openobserve/openobserve-helm-chart/assets/73132669/58c97f04-c7b6-4ff0-b66b-2a1ad1a49466)

**Comment by hengfeiyang** [comment]
https://github.com/openobserve/openobserve/releases/tag/v0.10.0

v0.10.x version can't rollback to v0.9.x it is an break version, Please upgrade all node to v0.10.1 first, then if you got any error, please tell us.

**Comment by ericsheris-rumble** [comment]
Full error when trying to run 0.10.1, everything is crashing with this 
```
openobserve-ingester thread 'main' panicked at /openobserve/src/service/db/schema.rs:405:9:
openobserve-ingester assertion `left == right` failed: BUG
openobserve-ingester   left: 3
openobserve-ingester  right: 4
openobserve-ingester stack backtrace:
openobserve-ingester    0:     0x563e50d3914b - <unknown>
openobserve-ingester    1:     0x563e4decb05c - <unknown>
openobserve-ingester    2:     0x563e50d354a3 - <unknown>
openobserve-ingester    3:     0x563e50d38eb4 - <unknown>
openobserve-ingester    4:     0x563e50d3a998 - <unknown>
openobserve-ingester    5:     0x563e50d3a680 - <unknown>
openobserve-ingester    6:     0x563e50d3ae9e - <unknown>
openobserve-ingester    7:     0x563e50d3ad92 - <unknown>
openobserve-ingester    8:     0x563e50d39636 - <unknown>
openobserve-ingester    9:     0x563e50d3aad4 - <unknown>
openobserve-ingester   10:     0x563e4d079445 - <unknown>
openobserve-ingester   11:     0x563e4d0798bf - <unknown>
openobserve-ingester   12:     0x563e4d11eeef - <unknown>
openobserve-ingester   13:     0x563e4feb0911 - <unknown>
openobserve-ingester   14:     0x563e4fe0eda5 - <unknown>
openobserve-ingester   15:     0x563e504ee3a0 - <unknown>
openobserve-ingester   16:     0x563e504e97b0 - <unknown>
openobserve-ingester   17:     0x563e500e7ec3 - <unknown>
openobserve-ingester   18:     0x563e500ecd3d - <unknown>
openobserve-ingester   19:     0x563e50d2b11a - <unknown>
openobserve-ingester   20:     0x563e504ffce5 - <unknown>
openobserve-ingester   21:     0x7fd650e2724a - <unknown>
openobserve-ingester   22:     0x7fd650e27305 - __libc_start_main
openobserve-ingester   23:     0x563e4d199ab1 - <unknown>
openobserve-ingester   24:                0x0 - <unknown>

```

**Comment by hengfeiyang** [comment]
Can you check the data in PostgreSQL:
```sql
select count(*) from meta where module='schema';
select count(*) from meta where module='schema' and start_dt=0;
select count(*) from meta where module='schema' and start_dt>0;
select * from meta where module='meta';
select * from meta where module='migration';
```

**Comment by ericsheris-rumble** [comment]
FYI, i was able to restore a backup from shortly before i attempted the upgrade and got myself running on 0.9.1. I do have the db I attempted to upgrade available so I can get your answers. Getting late here tho so any other questions i'll get to tomorrow
select count(*) from meta where module='schema';
273
select count(*) from meta where module='schema' and start_dt=0;
1
select count(*) from meta where module='schema' and start_dt>0;
272
select * from meta where module='meta';
```
module	id	key1	key2	value	start_dt
meta	3	kv	version	v0.10.1	0
```
select * from meta where module='migration';
```
id	module	key1	key2	value	start_dt
281,214	migration	schema_versions	status	1713488566467938	0
```

**Comment by hengfeiyang** [comment]
okay, delete the `start_dt=0` it should be fine.
```sql
delete from meta where start_dt=0;
```

I think the problem generated by you have multiple ingester when you upgrade to v0.10.0, it will auto-upgrade database schema, the first node upgrade done, but other ingesters still running with old version, the node can't recognize the new schema, and then insert a old format schema, it caused this problem.

Just delete the line, it should be working.

**Comment by hengfeiyang** [comment]
Or you can run like this:
```sql
select id,module,key1,key2 from meta where module='schema' and start_dt=0;
```

Then you will got the record, and then use the `id` to delete:
```
delete from meta where id=xxx
```

**Comment by ericsheris-rumble** [comment]
Ok, I doubt i'll actually migrate back to that old db so to confirm, so I can actually complete the upgrade from 0.9.1 > 0.10.1 successfully, I should:
Drop my 0.9.1 down to 1 ingester
update to 0.10.1
hopefully am then able to spin more ingesters back up if needed?

**Comment by hengfeiyang** [comment]
```
⚠️⚠️⚠️Once you start using this version, you shouldn't rollback to 0.9.x version, this version includes db changes , which are incompatible with previous versions. If applications is running in cluster mode please scale all deployments to zero only use single compactor to upgrade to v0.10.0 after upgrade and everything work well, we can scale up application to desired state.
```
https://github.com/openobserve/openobserve/releases/tag/v0.10.0

**Comment by ericsheris-rumble** [comment]
sorry one more quick question, does it matter if i go from 0.9.1 > 0.10.1 directly or should I do it in steps like 0.9.1 > 0.10.0 > 0.10.1?

**Comment by hengfeiyang** [comment]
0.10.1 is same to 0.10.0, just some bug fix, no major change.

**Comment by ericsheris-rumble** [comment]
Thanks, successfully completed the update.
