### ISSUE TITLE
Typo causing rendering issues

### ISSUE THREAD

**Issue by ShadowZero3000** [openobserve/openobserve-helm-chart#69]
https://github.com/openobserve/openobserve-helm-chart/blob/1e6a6420f8f83b32437b64f3aff5c28349f81753/charts/openobserve-standalone/templates/openobserve-statefulset.yaml#L16

Looks like the last commit may be missing a trailing bracket. (My first time trying this chart out, so apologies if I'm missing something)

**Comment by mlhynfield** [comment]
I also apologize if I'm missing something since I'm trying this out for the first time as well, but when should the chart version which includes this fix be released? Is there automation to release it or does it need to be done manually?

**Comment by prabhatsharma** [comment]
You are right. The chart was not published. Just published it. It is currently a manual activity.
