### ISSUE TITLE
Unknow Target in HPA.

### ISSUE THREAD

**Issue by ankitsnlq** [openobserve/openobserve-helm-chart#7]
Getting message in HPA Target Unknow. 

`NAME                                                           REFERENCE                              TARGETS                        MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/zo1-openobserve            Deployment/zo1-openobserve             <unknown>/80%, <unknown>/80%   1         100       0       177m
horizontalpodautoscaler.autoscaling/zo1-openobserve-ingester   Statefulset/zo1-openobserve-ingester   <unknown>/80%, <unknown>/80%   1         100       0`

deployments/scale.apps "zo1-openobserve" not found for both Deployment and similarly below message for no matches for kind "Statefulset" in group "apps"

Below is Values.yml for Autoscaling part. 

resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 300m
      memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

**Comment by matheusmazzoni** [comment]
@ankitsnlq are you installed metrics server?

**Comment by prabhatsharma** [comment]
@ankitsnlq I missed this one. Can you confirm if you have metrics server installed? - https://github.com/kubernetes-sigs/metrics-server. HPA requires metrics server to be installed (You could also use prometheus adapter - https://github.com/kubernetes-sigs/prometheus-adapter).

**Comment by prabhatsharma** [comment]
Closing it as stale
