### ISSUE TITLE
Built-in postgres deployment broken

### ISSUE THREAD

**Issue by Dennor** [openobserve/openobserve-helm-chart#73]
Hello, due to the combination of this two changes:
* https://github.com/openobserve/openobserve-helm-chart/commit/679eee6dfb22be2ca7bdd96267a85b8878d3b788
* https://github.com/openobserve/openobserve-helm-chart/commit/92ae06aaf45e95a91f3243449e913ea27db1cfe8

Built-in postgres no longer works, as the DSN for postgres is empty. The generated value in configmap gets overriden by the empty value in secret which lacks the generated condition branch.

**Comment by Dennor** [comment]
A little bit more detail, this lnie:
https://github.com/openobserve/openobserve-helm-chart/blob/5637901c241c9a9f2199441b2bd81b6b2a7eced0/charts/openobserve/templates/configmap.yaml#L70
does not do anything at this point, it adds a value to configmap, but that value is not considered due to secret priority.

**Comment by prabhatsharma** [comment]
```shell
cd charts/openobserve/
helm -n openobserve -f test_values.yaml template o2 . > o2.yaml
```

Do you get ZO_META_POSTGRES_DSN blank?

**Comment by prabhatsharma** [comment]
I got the issue.
