### ISSUE TITLE
Resource Configurations

### ISSUE THREAD

**Issue by pandakkkk** [openobserve/openobserve-helm-chart#8]
Recently, I successfully deployed it within our cluster. However, I am experiencing high CPU/memory utilization on the compactor and ingester components, while the alertmanager and router show normal usage patterns. I am now contemplating how we can assign distinct resource configurations for each of these components. I have already reviewed the template files, but I am curious if there are any plans to implement this change and what led to the current setup being designed in this manner.

**Comment by prabhatsharma** [comment]
Yeah, we are aware of this. We have plans to do that but just haven't been able to get to it. Will implement it shortly unless you would like to send a PR in that case it can be faster.
